export const majors = [
  { label: "Psychology", key: "psych" },
  { label: "Statistics", key: "stats" },
  { label: "Computer Science", key: "cs" },
  { label: "Business Administration", key: "busAdmin" },
  { label: "Music", key: "music" },
  { label: "Communications", key: "comm" },
  { label: "Criminal Justice", key: "criminal" },
  { label: "Social Work", key: "social" },
  { label: "Accounting", key: "accounting" },
  { label: "Business Management", key: "busMan" },
  { label: "Finance", key: "finance" },
  { label: "Mechanical Engineering", key: "mechE" },
  { label: "Civil Engineering", key: "civilE" },
  { label: "Chemical Engineering", key: "chemE" },
  { label: "Aerospace Engineering", key: "aeroE" },
  { label: "Nuclear Engineering", key: "nukeE" },
  { label: "Electrical Engineering", key: "eE" },
  { label: "Computer Engineering", key: "compE" },
  { label: "Nursing", key: "nurse" },
  { label: "Marketing", key: "market" },
  { label: "Biology", key: "bio" },
  { label: "Forensic Science", key: "forSci" },
  { label: "Hospitality", key: "home" },
  { label: "Economics", key: "econ" },
  { label: "Kinesiology", key: "kin" },
  { label: "Neuroscience", key: "neuro" },
  { label: "Mathematics", key: "math" },
  { label: "Spanish", key: "span" },
  { label: "Italian", key: "italian" },
  { label: "Russian", key: "russ" },
  { label: "Pharmacy", key: "pharma" },
  { label: "Architecture", key: "arch" },
  { label: "Sociology", key: "soc" },
  { label: "Nutrition", key: "food" },
  { label: "Interior Design", key: "int" },
  { label: "Graphic Design", key: "graphD" },
  { label: "Political Science", key: "polySci" },
  { label: "Anthropology", key: "anthro" },
  { label: "Education", key: "edu" },
  { label: "History", key: "History" },
  { label: "Linguistics", key: "ling" },
  { label: "Chemistry", key: "chem" },
  { label: "Zoologuy", key: "zoo" },
  { label: "Public Relations", key: "pub" },
  { label: "Journalism", key: "journal" },
  { label: "International Relations", key: "intR" },
  { label: "International Business", key: "intB" },
  { label: "Enviornmental Science", key: "envSci" },
  { label: "Physics", key: "physic" },
  { label: "Theology", key: "theo" },
  { label: "Biochemistry", key: "biochem" },
  { label: "Pre-law", key: "law" },
  { label: "Pre-med", key: "med" },
  { label: "Film", key: "film" },
  { label: "Agriculture", key: "agri" },
  { label: "Animal Science", key: "aniSci" },
  { label: "Photography", key: "photo" },
  { label: "Marine Biology", key: "marBio" },
  { label: "Data Science", key: "ds" },
  { label: "Sports Management", key: "sport" },
  { label: "Cybersecurity", key: "cyber" },
  { label: "Computer and Information Systems", key: "it" },
  { label: "English", key: "eng" },
];
